### PR TITLE
BXB-4438 Merge Upstream commit with fix for arm64 support.

### PR DESCRIPTION
**Pull request by MattMacGregor**
Merge this upstream commit for arm64 support.

> ZOOKEEPER-1643. Windows: fetch_and_add not 64bit-compatible, may not be correct (Erik Anderson via michim)
> 
> git-svn-id: https://svn.apache.org/repos/asf/zookeeper/trunk@1448007 13f79535-47bb-0310-9956-ffa450edef68 (cherry picked from commit 97e598b6c1068624ab6b6a663d3d40047589199a)

### CODE REVIEW

**Comment by artasano** [comment]
@MattMacGregor Have you tried it on some project, such as Bixby?

**Comment by MattMacGregor** [comment]
@artasano Yes, it has been tried with this bixby PR: https://github.com/yoinc/bixby/pull/1386

Will wait for the current build on the PR to succeed once again before merging this one to be safe, but it's built with it before.

**Comment by MattMacGregor** [comment]
> @artasano Yes, it has been tried with this bixby PR: [yoinc/bixby#1386](https://github.com/yoinc/bixby/pull/1386)
> 
> Will wait for the current build on the PR to succeed once again before merging this one to be safe, but it's built with it before.

In that Bixby PR it built fine, so I'm comfortable saying this is ready to merge. Automation suite completed fine.

**Comment by artasano** [comment]
Bixby automation does not explicitly test zookeeper registration of the bixby. If you have zookeeper server installed on your mac, you can run the bixby locally to see it correctly registers itself to the local zookeeper.
Another way is to run a Jenkins build and while the automation is running, figure out which automation environment it is running and check ZKWeb http://zk-web.eng.airtime.com/ by entering the automation zookeeper such as `zookeeper-1-automation820.eng.airtime.com:2181/` to the destination box.

**Review by artasano — APPROVED** [review]

**Review by sumitkandpal — APPROVED** [review]

**Comment by MattMacGregor** [comment]
While I was doing some digging to better understand the commit I cherrpicked here, I realized that automerge had screwed up the `CHANGES.txt` file. So I just went back and manually fixed it so it still makes sense and corresponds to the current changes. Also modified commit message to specified the charry-picked commit was slightly modified for `CHANGES.txt`.

**Review by artasano — APPROVED** [review]

**Review by bhanu-cantina — APPROVED** [review]

**Pull request merged**
